import { DevBlog } from '../models/dev-blog'

export const StubDevBlogs: DevBlog[] = [
    {title: "Hello World in Angular", date: new Date("2019-01-16"), body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies nulla ut urna laoreet finibus. Aenean sit amet euismod lacus, id accumsan dolor. Sed vel posuere justo. Aenean nisl quam, cursus a auctor vel, viverra at magna. Suspendisse potenti. Suspendisse potenti. Sed sollicitudin, mauris et iaculis vestibulum, neque dolor ultrices lacus, varius gravida diam elit non magna. Sed congue nunc vel eros blandit, sed dictum dui porta. In ut posuere magna, eu aliquet nisl. Morbi vitae neque lacinia, pellentesque arcu quis, molestie augue. Nam a nisl tellus." },
    {title: "Blockchain Microservice Generator", date: new Date("2020-01-16"), body: "Donec vel est leo. Maecenas et hendrerit lacus, quis auctor ligula. Nulla maximus dui et lorem cursus egestas. Mauris maximus enim et lectus finibus, sed tempus dolor gravida. Nam non magna eget mauris aliquam semper ac eget urna. Nulla facilisi. In eu nisi nibh. Integer dapibus vestibulum libero, feugiat dignissim quam scelerisque eu. Fusce accumsan lectus lectus, sit amet fringilla tortor convallis eget." },
    {title: "Tic-Tac-Toe or Something Like That", date: new Date("2020-01-16"), body: "Pellentesque ac erat orci. Aliquam erat volutpat. Vivamus et nibh et libero convallis tristique ut id metus. Praesent hendrerit ornare nibh quis tristique. Ut nisl purus, ultricies at nibh vel, posuere interdum elit. Aliquam finibus, risus eu vulputate ullamcorper, nunc risus mollis nisi, eu venenatis neque magna nec risus. Duis efficitur quam vel enim ullamcorper sagittis. Curabitur ut volutpat erat, eu fringilla ante. Nulla pulvinar diam at dolor faucibus, nec tincidunt massa vehicula. Morbi eros ipsum, mattis venenatis posuere non, blandit vel enim. Ut pulvinar nisi vel malesuada fringilla. Cras id ipsum ex. Mauris mollis vulputate orci non iaculis. Maecenas sit amet erat et lorem venenatis consectetur. Suspendisse pretium elit id elit vestibulum, nec fringilla nunc varius." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." },
    {title: "Portfolio Site", date: new Date("2020-08-30"), body: "Morbi sed sodales urna. Cras vestibulum ante nulla, quis tincidunt nisl feugiat vel. Ut in consectetur neque. Duis convallis maximus lorem ac varius. Donec euismod id nulla id egestas. Proin vitae tortor ipsum. Donec porta id urna at sodales. Mauris mattis est nec suscipit rutrum." }
]
